### ISSUE TITLE
Saturation curve 

### ISSUE THREAD

**Issue by trappitsch** [RIMS-Code/rimsdb_scheme_submission#1]
Add the following capabilities to saturation curves.

- [x] Sorting in the table (up and down) #4 
- [x] Overwriting existing one (if same title) #5 
- [x] Loading of a stored one for editing #5
